complex.html review
akronb/yard-frontend pull request #1
Opened 2017-06-12 23:05 UTC by akronb

2017-06-13 10:21 UTC, imevro requested changes
https://www.dropbox.com/s/r9qydmbp1z02s46/Screenshot%202017-06-13%2013.21.40.png?dl=0

2017-06-13 11:20 UTC, akronb reviewed
fixed flexbox img problem

2017-06-13 12:21 UTC, imevro requested changes
https://validator.w3.org/nu/?doc=https%3A%2F%2Frawgit.com%2Fakronb%2Fyard-frontend%2Fe48219c41224dc3a7687c3e52fa7a0e258c7b4d4%2Fcomplexes.html

2017-06-14 13:25 UTC, imevro requested changes
Пофикси баг с сеткой, в телеграме присылал.

2017-06-14 13:25 UTC, evgenyrodionov commented on style.css
> +.wrap {
wrapper логичнее

2017-06-14 19:00 UTC, imevro requested changes

2017-06-14 19:00 UTC, evgenyrodionov commented on style.css
> +.wrapper {
В чём смысл? Есть же контейнер из фбг

2017-06-14 19:00 UTC, evgenyrodionov commented on style.css
> +.footer-header {
футер-хедер? Мощь

2017-06-14 19:00 UTC, evgenyrodionov commented on style.css
> +.footer-list-start {
старт?

2017-06-14 19:00 UTC, evgenyrodionov commented on style.css
> +.footer-list-start {
divider, border

2017-06-14 19:00 UTC, evgenyrodionov commented on complexes.html
> +               ИНН 5036165365<br>
бры это плохо

2017-06-14 19:00 UTC, evgenyrodionov commented on complexes.html
> +            <ul class="footer-list">
Не думаю что тут есть необходимость в списке, а необходимость в семантичном `<nav>` — весьма

2017-06-14 19:04 UTC, akronb commented on style.css
> +.footer-header {
There are only two hard things in Computer Science: cache invalidation and naming things.

-- Phil Karlton

2017-06-14 21:06 UTC, imevro approved these changes

2017-06-14 21:07 UTC, merged

2017-06-14 21:07 UTC, evgenyrodionov commented
Делаешь `git pull --rebase` теперь