feat/new api
akronb/yard-frontend pull request #11
Opened 2017-07-07 16:57 UTC by akronb

Новый api в процессе, отправил на промежуточную проверку

2017-07-07 17:00 UTC, evgenyrodionov commented
Промежуточных не бывает

2017-07-08 02:24 UTC, akronb commented
Прикрутил новый api, добавил mapbox

2017-07-08 09:29 UTC, imevro requested changes

2017-07-08 09:29 UTC, evgenyrodionov commented on src/Complexes/Show/Infrastructure.jsx
> +          {amenities.map(data =>
дата слишком общий нейминг

2017-07-08 09:29 UTC, evgenyrodionov commented on src/Complexes/Show/Location.jsx
> +import Map from './Map';
Покушение на резервед слово https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Map

2017-07-08 13:09 UTC, imevro approved these changes

2017-07-08 13:10 UTC, merged