feat/carousel
akronb/yard-frontend pull request #12
Opened 2017-07-11 15:05 UTC by akronb

https://build-ojlzvnjsjp.now.sh

2017-07-12 08:11 UTC, akronb commented
https://build-bvovdmhttq.now.sh/complexes/2

переделал на transform: scale

2017-07-12 12:53 UTC, evgenyrodionov commented
У крайних пикч должен быть опасити

2017-07-12 12:53 UTC, evgenyrodionov commented
и разберись с открытием галереи

2017-07-12 12:54 UTC, evgenyrodionov commented
но ваще круто

2017-07-12 12:54 UTC, evgenyrodionov commented
но ваще круто

2017-07-12 12:54 UTC, evgenyrodionov commented
и не делай хейт 88%, делай transform scale 0.8

2017-07-12 21:27 UTC, akronb commented
https://build-bofgsuxbdh.now.sh

2017-07-13 09:35 UTC, evgenyrodionov commented
Доделай ховер

2017-07-15 16:57 UTC, akronb commented
https://build-ckiuqnjdfx.now.sh

2017-07-15 17:22 UTC, imevro requested changes

2017-07-15 17:22 UTC, evgenyrodionov commented on src/Complexes/Show/Carousel.jsx
> +            openByClickOn={
лучше пропами держать, это говно неудобное

2017-07-15 17:22 UTC, evgenyrodionov commented on src/Complexes/Show/Carousel.jsx
> +            <Slideshow images={props.images} name={props.name} activeSlide={index} />
просто эктив

2017-07-15 17:22 UTC, evgenyrodionov commented on src/Complexes/Show/Carousel.jsx
> +            <Slideshow images={props.images} name={props.name} activeSlide={index} />
а также не понял почему эктив у тебя каждый элемент массива, это как?

2017-07-15 17:22 UTC, evgenyrodionov commented on src/Complexes/Show/Carousel.jsx
> +        <Portal closeOnEsc openByClickOn={ModalButton}>
еще раз? не понял

2017-07-15 17:22 UTC, evgenyrodionov commented on src/Complexes/Show/Carousel.jsx
> +        <Portal closeOnEsc openByClickOn={ModalButton}>
это чтобы по клику открывалось что ли?

2017-07-15 17:22 UTC, evgenyrodionov commented on src/Complexes/Show/Carousel.jsx
> +        <Portal closeOnEsc openByClickOn={ModalButton}>
так храни в стейте активный индекс и передавай внутрь чтобы отцентрировать

2017-07-15 17:22 UTC, evgenyrodionov commented on src/Complexes/Show/Slideshow.jsx
> +    if (this.state.justOpened) this.setState({ justOpened: false });
не клево вообще

2017-07-15 17:22 UTC, evgenyrodionov commented on src/Complexes/Show/Slideshow.jsx
> +    let mainStyle;
без мутабельности

2017-07-15 17:22 UTC, evgenyrodionov commented on src/Complexes/Show/Slideshow.jsx
> +    event.stopPropagation();
это хорошо?

2018-01-20 14:41 UTC, merged