feat/complex-adaptive
akronb/yard-frontend pull request #14
Opened 2017-07-25 16:34 UTC by akronb

https://build-cfpelhipoa.now.sh

2017-07-25 20:38 UTC, evgenyrodionov commented
Антон, это очень красиво

![image](https://user-images.githubusercontent.com/775692/28592617-4ab6b7fa-7192-11e7-9e35-81d747924011.png)

2017-07-26 06:41 UTC, akronb commented
У now вчера [были проблемы](https://twitter.com/zeithq/status/890000356339576832), поэтому билд был такой **_красивый_**

2017-07-26 08:15 UTC, evgenyrodionov commented
Апдейтни зум

2017-07-26 08:15 UTC, imevro approved these changes

2017-07-26 11:17 UTC, akronb commented
https://build-ykdetbnsvp.now.sh

2017-07-27 11:19 UTC, akronb commented
со старым API https://build-ztvmldbyud.now.sh

2017-07-27 17:49 UTC, imevro requested changes

2017-07-27 17:49 UTC, evgenyrodionov commented on src/Complexes/Show/Infrastructure.jsx
> +    &:nth-child(6n + 1) {
не нравятся такие селекторы магические

2017-07-28 16:10 UTC, akronb commented
https://build-azwndeexkm.now.sh

2017-08-01 18:32 UTC, evgenyrodionov commented
Исправь, нигга

![image](https://user-images.githubusercontent.com/775692/28840842-f2e978b8-7700-11e7-99ed-362274e7f063.png)

2017-08-09 15:53 UTC, akronb commented
https://build-ovraqjpqed.now.sh

2018-01-20 14:38 UTC, merged