feat/complexes-page-on-react
akronb/yard-frontend pull request #3
Opened 2017-06-20 16:55 UTC by akronb

Перевел complexes.html на реакт, выделил футер и хедер в компоненты

2017-06-20 17:47 UTC, imevro requested changes

2017-06-20 17:47 UTC, evgenyrodionov commented on src/App.css
> +  -webkit-box-pack: justify;
кра сам префиксует

2017-06-20 17:47 UTC, evgenyrodionov commented on src/App.js
> +    <div className="App">
поставь преттир

2017-06-24 11:49 UTC, akronb commented
Добавил поддержку eslint

2017-06-24 13:55 UTC, imevro approved these changes

2017-06-24 13:56 UTC, merged