feat/flow
akronb/yard-frontend pull request #8
Opened 2017-06-30 15:10 UTC by akronb

2017-06-30 19:05 UTC, imevro requested changes
короче распиши полностью данные

2017-06-30 19:05 UTC, evgenyrodionov commented on .eslintrc
> +    "plugin:flowtype/recommended"
nope

2017-06-30 19:05 UTC, evgenyrodionov commented on package.json
> +    "ft": "flow-typed install"
не оч очевидно, лучше `flow:install`

2017-06-30 19:05 UTC, evgenyrodionov commented on src/Complexes/Show/Carousel.jsx
> +  images: Array<Object>,
распиши

2017-06-30 19:05 UTC, evgenyrodionov commented on src/Complexes/Show/Header.jsx
> +  postalCode: string,
?string

2017-06-30 19:05 UTC, evgenyrodionov commented on src/Complexes/Show/Header.jsx
>    return [address, postalCode].filter(item => !!item).join(' • ');
чё-т ты увлекся фильтрами и джойном, верни тупо две разных строки

2017-06-30 19:05 UTC, evgenyrodionov commented on src/Complexes/Show/Header.jsx
>    return [address, postalCode].filter(item => !!item).join(' • ');
хотя забавно конечно, можно даже оставить

2017-07-01 13:52 UTC, imevro requested changes
заведи лучше несколько типов типа Image, Location и экспорти их из тайп, $PropertyType выглядит как костыль

2017-07-01 13:52 UTC, evgenyrodionov commented on src/Complexes/Show/Carousel.jsx
> +      {props.images.length > 0 &&
зачем эта проверка? если тебе придет пустой массив, он тупо не будет итерироваться. Если тебе не придет массив, то почему?

2017-07-01 13:52 UTC, evgenyrodionov commented on src/Complexes/Show/index.jsx
> +  state: Complex = {
почему из тайпс не достаешь?

2017-07-01 21:06 UTC, imevro requested changes

2017-07-01 21:06 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +import type { ComplexTypes, LocationTypes } from '../types';
поч во множ числе

2017-07-01 21:06 UTC, evgenyrodionov commented on src/Complexes/types.js
> +  images?: ImagesTypes,
лучше опиши как `Array<ImageType>`

2017-07-01 21:06 UTC, evgenyrodionov commented on src/Complexes/types.js
> +  images?: ImagesTypes,
имджс это обязательное поле, посмотри модель

2017-07-01 21:54 UTC, imevro approved these changes

2017-07-01 21:54 UTC, merged